import os
import json
import re
import urllib.request

def parse_markdown_file(file_path, filename):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Default metadata
    title = os.path.splitext(filename)[0].replace("-", " ").title()
    date = ""
    status = "Draft"
    owner = "General"
    lang = "ar" if "-ar" in filename else "en"
    direction = "rtl" if lang == "ar" else "ltr"

    # Try parsing front matter
    front_matter_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    markdown_content = content
    if front_matter_match:
        front_matter = front_matter_match.group(1)
        markdown_content = content[front_matter_match.end():]
        # Simple YAML-like parsing
        for line in front_matter.split("\n"):
            if ":" in line:
                k, v = line.split(":", 1)
                k = k.strip().lower()
                v = v.strip().strip('"').strip("'")
                if k == "title": title = v
                elif k == "date": date = v
                elif k == "status": status = v
                elif k == "owner": owner = v
                elif k == "lang": 
                    lang = v
                    direction = "rtl" if lang == "ar" else "ltr"
    else:
        # No front matter: parse first # header and look for metadata lines
        first_h1 = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
        if first_h1:
            title = first_h1.group(1).strip()

        # Look for metadata lines like Date: ..., Status: ..., Owner: ...
        date_match = re.search(r"^Date:\s*(.+)$", content, re.MULTILINE | re.IGNORECASE)
        if date_match:
            date = date_match.group(1).strip()
        
        status_match = re.search(r"^Status:\s*(.+)$", content, re.MULTILINE | re.IGNORECASE)
        if status_match:
            status = status_match.group(1).strip()
            
        owner_match = re.search(r"^Owner:\s*(.+)$", content, re.MULTILINE | re.IGNORECASE)
        if owner_match:
            owner = owner_match.group(1).strip()

    # Calculate reading time (roughly 200 words per minute)
    words_count = len(re.findall(r"\w+", markdown_content))
    reading_time = max(1, round(words_count / 200))

    return {
        "id": os.path.splitext(filename)[0],
        "title": title,
        "filename": filename,
        "content": markdown_content,
        "metadata": {
            "date": date,
            "status": status,
            "owner": owner,
            "lang": lang,
            "direction": direction,
            "readingTime": reading_time
        }
    }

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    docs_dir = os.path.join(script_dir, "..", "docs")
    output_js_path = os.path.join(script_dir, "docs-data.js")
    marked_path = os.path.join(script_dir, "marked.min.js")

    print(f"Scanning docs directory: {docs_dir}")
    if not os.path.exists(docs_dir):
        print(f"Error: {docs_dir} does not exist.")
        return

    documents = []
    
    # Prioritize README.md to be the first one in the list (main page)
    readme_path = os.path.join(docs_dir, "README.md")
    if os.path.exists(readme_path):
        doc = parse_markdown_file(readme_path, "README.md")
        doc["title"] = "Overview"
        documents.append(doc)

    for filename in sorted(os.listdir(docs_dir)):
        if filename.endswith(".md") and filename != "README.md":
            file_path = os.path.join(docs_dir, filename)
            doc = parse_markdown_file(file_path, filename)
            documents.append(doc)
            print(f"Parsed: {filename} ({doc['metadata']['lang']})")

    # Save to docs-data.js
    with open(output_js_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build.py. Do not edit.\n")
        f.write(f"const docsData = {json.dumps(documents, indent=2, ensure_ascii=False)};\n")
    print(f"Successfully generated data bundle: {output_js_path}")

    # Download marked.min.js if not exists
    if not os.path.exists(marked_path):
        marked_url = "https://cdn.jsdelivr.net/npm/marked@12.0.0/lib/marked.umd.min.js"
        print(f"Downloading marked.js library from {marked_url}...")
        try:
            urllib.request.urlretrieve(marked_url, marked_path)
            print(f"Successfully downloaded marked.js to {marked_path}")
        except Exception as e:
            print(f"Failed to download marked.js from CDN: {e}")
            print("Will fall back to CDN link in HTML if local copy fails.")

if __name__ == "__main__":
    main()
